INSERT INTO Films (titre, synopsis, genre, annee, duree, affiche, url_film, urlBA)
VALUES
    ('Sketch FIE4 Promo 2022', 'Un sketch réalisé par la promo FIE4 2022', 'Comédie', 2021, '15min08', NULL, '', NULL),
    ('The Hospital 1', 'Premier volet de The Hospital', 'Comédie', 2022, '13min54', NULL, '', NULL),
    ('The Hospital 3', 'Troisième volet de The Hospital', 'Comédie', 2023, '14min28', '/images/thehospital3.jpg', '', NULL),
    ('The Hospital 4', 'Quatrième volet de The Hospital', 'Comédie', 2024, '15min08', '/images/thehospital4.jpg','', NULL);

INSERT INTO Participants (nom, prenom, pdp) VALUES
                                                ('DUPUY', 'Emma', NULL),
                                                ('SALVAN', 'Emma', NULL),
                                                ('DON', 'Marie-Laure', NULL),
                                                ('SADGAL', 'Rania', NULL),
                                                ('BARBOT', 'Mattéo', NULL),
                                                ('CABANES', 'Ulysse', NULL),
                                                ('GOETSCHEL', 'Numa', NULL),
                                                ('VICHET', 'Victoria', NULL),
                                                ('CHANAL', 'Marie', NULL),
                                                ('LEONE', 'Julie', NULL),
                                                ('FAUCHER', 'Ruby', NULL),
                                                ('MARTY', 'Morgan', NULL),
                                                ('CANAVY', 'Marisol', NULL),
                                                ('HENRY', 'Camille', NULL),
                                                ('ROGERS', 'Nelson', NULL),
                                                ('ABITBOL', 'Lucas', NULL),
                                                ('AIT YOUSEF', 'Wassim', NULL),
                                                ('DELESTRE', 'Clémence', NULL),
                                                ('REGHEM', 'Romain', NULL),
                                                ('MAJID', 'Saif', NULL),
                                                ('BOUILLET', 'Benjamin', NULL),
                                                ('JOVIGNOT', 'Noah', NULL),
                                                ('CUISOT', 'Mallory', NULL),
                                                ('GOBIN', 'Rémi', NULL),
                                                ('LARTOT', 'Alexis', NULL),
                                                ('BESSE', 'Vincent', NULL),
                                                ('MERCIER', 'Lara', NULL),
                                                ('BRUNET', 'Enora', NULL),
                                                ('SAHAGUIAN', 'Solan', NULL),
                                                ('DORTE', 'Romain', NULL),
                                                ('VIEILLARD', 'Antoine', NULL),
                                                ('LAHMIDI', 'Soukaïna', NULL),
                                                ('CHAUBET', 'Paul', NULL),
                                                ('MASSIAS', 'Paul', NULL),
                                                ('JOLIVET', 'Anaëlle', NULL),
                                                ('BONNAFOUS', 'Arnaud', NULL),
                                                ('MATTONE', 'Elsa', NULL),
                                                ('DELMAS', 'Léo', NULL),
                                                ('ORTEGA', 'Paul', NULL),
                                                ('AYMARD', 'Marion', NULL),
                                                ('KESKIN', 'Defne', NULL),
                                                ('HAJJAM', 'Ikhlass', NULL),
                                                ('EVRARD', 'Damien', NULL),
                                                ('RAYNAL', 'Mathilde', NULL),
                                                ('VILLEDIEU', 'Baptiste', NULL),
                                                ('LASSERVARIE', 'Gabin', NULL),
                                                ('BOURDARIAS', 'Cléa', NULL),
                                                ('ACHER', 'Solène', NULL),
                                                ('BOLZAN', 'Lucie', NULL),
                                                ('ZIDOUR', 'Chérine', NULL),
                                                ('ELIE', 'Antoine', NULL),
                                                ('GATIEN', 'Grégory', NULL),
                                                ('RENUCCI', 'Chloé', NULL),
                                                ('KUBALE', 'Magdalena', NULL),
                                                ('YAGUIYAN', 'Arnaud', NULL),
                                                ('GATIEN', 'Grégory', NULL),
                                                ('ACHER', 'Solène', NULL),
                                                ('TAISNE', 'Lucas', '/images/lucastaisne.jpg'),
                                                ('SOSSEY ALAOUI', 'Léopold', NULL),
                                                ('LEROY', 'Guillaume', NULL),
                                                ('BOUDRIGA', 'Sarra', NULL),
                                                ('TOUJENI', 'Imen', NULL),
                                                ('MEHL-PALMIE', 'Matis', NULL),
                                                ('DELBOS', 'Lucille', NULL),
                                                ('DUPE', 'Cassandra', NULL),
                                                ('COURREDE', 'Félix', NULL),
                                                ('REZOUKI', 'Rokaya', NULL),
                                                ('O’NEILL', 'Kevin', NULL),
                                                ('LOCK-FAT', 'Amélie', NULL),
                                                ('BAAZAOUI', 'Chaima', NULL),
                                                ('LIPOVAC', 'Noémi', NULL),
                                                ('AUBER', 'Colline', NULL),
                                                ('TOTI', 'Mathis', NULL),
                                                ('BERLABI', 'Ellee', NULL),
                                                ('ORTEGA', 'Zafiro', NULL),
                                                ('BONIN', 'Lenny', NULL),
                                                ('RIGAUD', 'Toinou', NULL),
                                                ('DE MONTEVY', 'Agathe', NULL),
                                                ('CHAUVEL', 'Justine', NULL),
                                                ('LAUDE', 'Camille', NULL),
                                                ('GROSJEAN', 'Alexandre', NULL),
                                                ('LEVENT', 'Romaine', NULL),
                                                ('CHANAL', 'Laura', NULL),
                                                ('SUBIRA', 'Emma', NULL),
                                                ('GRUEL', 'Alexis', NULL),
                                                ('BARTHE', 'Emma', NULL),
                                                ('BONNIN', 'Lenny', NULL),
                                                ('TOTI', 'Mathis', NULL),
                                                ('SZCZEPANSKI', 'Neo', NULL),
                                                ( 'GUENNOC', 'Dénoëla', NULL),
                                                (NULL, 'Léandre', NULL);

INSERT INTO Commentaires (description, id_film) VALUES
                                                                 ('Un excellent film avec une intrigue captivante.', 1),
                                                                 ('Les acteurs ont fait un travail remarquable.', 2);

INSERT INTO Images (img, id_film) VALUES
                                             ('/images/tournage.jpg', 4),
                                             ('/images/tournage2.jpg', 4),
                                             ('/images/CHL.jpg', 4),
                                             ('/images/accueil.jpg', 4),
                                             ('/images/CHL2.jpg', 4),
                                             ('/images/reflexion.jpg', 4),
                                             ('/images/backstage.jpg', 4);

INSERT INTO ADMINISTRATEURS (email, password) VALUES ('admin@example.com', '$2a$10$bI4I1CZSy93e425U9zGVoOY7vbB1gevrHAaqHWG0TYpJ.08dx5.Ey');

INSERT INTO Actualites (lien) VALUES
                                  ('https://www.youtube.com/watch?v=njgNtDXYPzs'),
                                  ('https://www.youtube.com/watch?v=zZRFJyzFgJQ'),
                                  ('https://www.youtube.com/watch?v=2Wu3Q_TyUnw&t=2s');

INSERT INTO Moments (titre, nom_img, description) VALUES
                                                       ('Première du film', '/images/premiere.jpg', 'La première du film a eu lieu hier soir.');

INSERT INTO joue (FILM_ID, PARTICIPANT_ID, ROLE, GROUPE) VALUES
                                                             (1, 1, 'Acteur', 'Acteur'),
                                                             (1, 2, 'Acteur', 'Acteur'),
                                                             (1, 3, 'Acteur', 'Acteur'),
                                                             (1, 4, 'Acteur', 'Acteur'),
                                                             (1, 5, 'Acteur', 'Acteur'),
                                                             (1, 6, 'Acteur', 'Acteur'),
                                                             (1, 7, 'Acteur', 'Acteur'),
                                                             (1, 8, 'Acteur', 'Acteur'),
                                                             (1, 9, 'Acteur', 'Acteur'),
                                                             (1, 10, 'Acteur', 'Acteur'),
                                                             (1, 11, 'Acteur', 'Acteur'),
                                                             (1, 12, 'Acteur', 'Acteur'),
                                                             (1, 13, 'Acteur', 'Acteur'),
                                                             (2, 14, 'Britney', 'Acteur'),
                                                             (2, 15, 'Alex', 'Acteur'),
                                                             (2, 16, 'Marge', 'Acteur'),
                                                             (2, 17, 'Joey', 'Acteur'),
                                                             (2, 18, 'Karen', 'Acteur'),
                                                             (2, 19, 'Junior Doctor', 'Acteur'),
                                                             (2, 20, 'Doctor', 'Acteur'),
                                                             (2, 21, 'Director', 'EquipeDeTournage'),
                                                             (2, 22, 'Script', 'EquipeDeTournage'),
                                                             (2, 23, 'Camera Operator', 'EquipeDeTournage'),
                                                             (2, 24, 'Boom Operator', 'EquipeDeTournage'),
                                                             (2, 91, 'Sound', 'EquipeDeTournage'),
                                                             (2, 24, 'Editor', 'PostProduction'),
                                                             (2, 21, 'Koh Lanta’s part Editor', 'PostProduction'),
                                                             (2, 22, 'Next’s part Supervisor', 'PostProduction'),
                                                             (2, 25, 'Next’s part Animations', 'PostProduction'),
                                                             (2, 90, 'Make up Artist', 'EquipeDeTournage'),
                                                             (3, 26, 'Director', 'EquipeDeTournage'),
                                                             (3, 27, 'Director of Photography', 'EquipeDeTournage'),
                                                             (3, 28, 'Editor', 'PostProduction'),
                                                             (3, 29, 'Editor', 'PostProduction'),
                                                             (3, 30, 'Music Composer', 'PostProduction'),
                                                             (3, 31, 'Music Composer', 'PostProduction'),
                                                             (3, 32, 'First Assistant Director', 'EquipeDeTournage'),
                                                             (3, 28, 'Second Assistant Director', 'EquipeDeTournage'),
                                                             (3, 33, 'Doctor Mean', 'Acteur'),
                                                             (3, 34, 'Doctor Donald', 'Acteur'),
                                                             (3, 35, 'Doctor Karen', 'Acteur'),
                                                             (3, 36, 'Doctor Grouch', 'Acteur'),
                                                             (3, 37, 'Skater Girl', 'Acteur'),
                                                             (3, 38, 'IT Luigi', 'Acteur'),
                                                             (3, 39, 'IT Mario', 'Acteur'),
                                                             (3, 40, 'Interviewer', 'Acteur'),
                                                             (3, 41, 'Patient 1', 'Acteur'),
                                                             (3, 42, 'Patient 2', 'Acteur'),
                                                             (3, 43, 'Patient 3', 'Acteur'),
                                                             (3, 44, 'Patient 4', 'Acteur'),
                                                             (3, 45, 'Patient 5', 'Acteur'),
                                                             (3, 46, 'Patient 6', 'Acteur'),
                                                             (3, 47, 'Chemist', 'Acteur'),
                                                             (3, 48, 'Sound Operator', 'EquipeDeTournage'),
                                                             (3, 29, 'First Assistant Sound', 'EquipeDeTournage'),
                                                             (3, 49, 'Camera Operator', 'EquipeDeTournage'),
                                                             (3, 50, 'Camera Operator', 'EquipeDeTournage'),
                                                             (3, 51, 'First Assistant Camera', 'EquipeDeTournage'),
                                                             (3, 30, 'First Assistant Camera', 'EquipeDeTournage'),
                                                             (3, 27, 'Chief Lighting Technician', 'EquipeDeTournage'),
                                                             (3, 52, 'Assistant Chief Lighting Technician', 'EquipeDeTournage'),
                                                             (3, 53, 'Assistant Chief Lighting Technician', 'EquipeDeTournage'),
                                                             (3, 54, 'Script', 'EquipeDeTournage'),
                                                             (3, 55, 'Chief Sound Editor', 'PostProduction'),
                                                             (3, 30, 'Music Compositor', 'PostProduction'),
                                                             (3, 31, 'Music Compositor', 'PostProduction'),
                                                             (3, 52, 'Color Calibration', 'PostProduction'),
                                                             (3, 30, 'Color Calibration', 'PostProduction'),
                                                             (3, 48, 'Film Poster and Credits', 'PostProduction'),
                                                             (3, 28, 'Visual Effects Supervisor', 'PostProduction'),
                                                             (4, 58, 'IT', 'Acteur'),
                                                             (4, 59, 'Director', 'EquipeDeTournage'),
                                                             (4, 60, 'IT Geek', 'Acteur'),
                                                             (4, 61, 'Carer', 'Acteur'),
                                                             (4, 62, 'Mrs Jude', 'Acteur'),
                                                             (4, 63, 'Ambulance Driver', 'Acteur'),
                                                             (4, 64, 'Mrs Brand', 'Acteur'),
                                                             (4, 65, 'Receptionist', 'Acteur'),
                                                             (4, 66, 'Mr O’Dea', 'Acteur'),
                                                             (4, 64, 'Dr Smart', 'Acteur'),
                                                             (4, 68, 'Vasectomy Doctor', 'Acteur'),
                                                             (4, 69, 'Nurse', 'Acteur'),
                                                             (4, 70, 'Patient', 'Acteur'),
                                                             (4, 71, 'Patient’s Friend', 'Acteur'),
                                                             (4, 72, 'Dr Bolonski', 'Acteur'),
                                                             (4, 73, 'Camera', 'EquipeDeTournage'),
                                                             (4, 74, 'Camera', 'EquipeDeTournage'),
                                                             (4, 75, 'First Assistant Director', 'EquipeDeTournage'),
                                                             (4, 76, 'Continuity Supervisor', 'EquipeDeTournage'),
                                                             (4, 77, 'Sound', 'EquipeDeTournage'),
                                                             (4, 78, 'Sound', 'EquipeDeTournage'),
                                                             (4, 79, 'Sound', 'EquipeDeTournage'),
                                                             (4, 80, 'Gaffers', 'EquipeDeTournage'),
                                                             (4, 81, 'Gaffers', 'EquipeDeTournage'),
                                                             (4, 82, 'Gaffers', 'EquipeDeTournage'),
                                                             (4, 83, 'Set Decoration', 'EquipeDeTournage'),
                                                             (4, 84, 'Set Decoration', 'EquipeDeTournage'),
                                                             (4, 85, 'Set Decoration', 'EquipeDeTournage'),
                                                             (4, 89, 'Grips', 'EquipeDeTournage'),
                                                             (4, 86, 'Grips', 'EquipeDeTournage'),
                                                             (4, 87, 'Editors', 'PostProduction'),
                                                             (4, 85, 'Editors', 'PostProduction'),
                                                             (4, 88, 'Colorist', 'PostProduction'),
                                                             (4, 89, 'Colorist', 'PostProduction'),
                                                             (4, 84, 'Poster and Opening by', 'PostProduction'),
                                                             (4, 83, 'Making of', 'PostProduction'),
                                                             (4, 75, 'Making of', 'PostProduction');

INSERT INTO Anecdotes (description, id_film, id_participant) VALUES
                                                                          ('Une scène a été tournée en une seule prise.', 1, 1),
                                                                          ('Les acteurs ont improvisé certaines répliques.', 2, 2),
                                                                          ('Je me suis viandé dans un vase quand j''ai été figurant lors du tournage de la séquence 10 (la séquence d''apocalypse dans l''hôpital). Je me suis partiellement cassé l''ongle à cause de ça x)', 4, 85),
                                                                          ('Après le tournage, nous nous sommes rendus compte que des fichiers/rushs ont tout bonnement disparu (au moins deux tiers d''une des deux caméras). On était dégoûtés.. ça représentait des heures de tournages qui s''étaient envolés.', 4, 58),
                                                                          ('Le tournage s''est vraiment bien passé, nous avons tout bouclé en une journée et nous n''avons pas arrêté haha. ', 4, 58);

